Add lab2 sources
ThinkingFrog/Operating-Systems-labs-2023 pull request #2
Opened 2023-11-24 10:11 UTC by ThinkingFrog

2023-11-26 17:34 UTC, DariaWelt requested changes
Нет возможности ввести число самостоятельно. В остальном ок.

2023-11-26 17:34 UTC, DariaWelt commented on lab2/Makefile
Этот файл не нужен.

2023-11-26 17:34 UTC, DariaWelt commented on lab2/host/client_info.hpp
> +    sem_t *sem_host_msg;
Можно было бы использовать unique_ptr с кастомными делитерами, выглядело бы понятнее

2023-11-26 17:34 UTC, DariaWelt commented on lab2/host/client_info.hpp
> +    int client_id;
```suggestion
    unsigned int client_id;
```

2023-11-28 15:13 UTC, ThinkingFrog commented on lab2/Makefile
Удалил

2023-11-29 20:45 UTC, DariaWelt approved these changes
Работа зачтена

2023-11-29 20:45 UTC, merged